// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OperationMaps.Infrastructure.Persistence;

#nullable disable

namespace OperationMaps.Infrastructure.src.OperationMaps.infrastructure.Persistence.Migrations.Catalog
{
    [DbContext(typeof(CatalogDbContext))]
    [Migration("20260530233844_InitialCatalog")]
    partial class InitialCatalog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("OperationMaps.Domain.Entities.Catalog.Component", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Designation")
                        .HasColumnType("TEXT");

                    b.Property<int>("FamilyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FamilyId");

                    b.HasIndex("FullName")
                        .IsUnique();

                    b.ToTable("Components");
                });

            modelBuilder.Entity("OperationMaps.Domain.Entities.Catalog.ComponentNote", b =>
                {
                    b.Property<int>("ComponentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FormParameterId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NoteId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ComponentId", "FormParameterId", "NoteId");

                    b.HasIndex("FormParameterId");

                    b.HasIndex("NoteId");

                    b.ToTable("ComponentNotes");
                });

            modelBuilder.Entity("OperationMaps.Domain.Entities.Catalog.ComponentNtdValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ComponentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FormParameterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ComponentId");

                    b.HasIndex("FormParameterId");

                    b.ToTable("ComponentNtdValues");
                });

            modelBuilder.Entity("OperationMaps.Domain.Entities.Catalog.ComponentPinValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ComponentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FormParameterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Pins")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ComponentId");

                    b.HasIndex("FormParameterId");

                    b.ToTable("ComponentPinValues");
                });

            modelBuilder.Entity("OperationMaps.Domain.Entities.Catalog.ComponentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ComponentTypes");
                });

            modelBuilder.Entity("OperationMaps.Domain.Entities.Catalog.Family", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ComponentTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ComponentTypeId", "Name")
                        .IsUnique();

                    b.ToTable("Families");
                });

            modelBuilder.Entity("OperationMaps.Domain.Entities.Catalog.FamilyForm", b =>
                {
                    b.Property<int>("FamilyId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FormId")
                        .HasColumnType("INTEGER");

                    b.HasKey("FamilyId", "FormId");

                    b.HasIndex("FormId");

                    b.ToTable("FamilyForms");
                });

            modelBuilder.Entity("OperationMaps.Domain.Entities.Catalog.FamilyNote", b =>
                {
                    b.Property<int>("FamilyId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FormParameterId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NoteId")
                        .HasColumnType("INTEGER");

                    b.HasKey("FamilyId", "FormParameterId", "NoteId");

                    b.HasIndex("FormParameterId");

                    b.HasIndex("NoteId");

                    b.ToTable("FamilyNotes");
                });

            modelBuilder.Entity("OperationMaps.Domain.Entities.Catalog.FamilyNtdValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FamilyId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FormParameterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FamilyId");

                    b.HasIndex("FormParameterId");

                    b.ToTable("FamilyNtdValues");
                });

            modelBuilder.Entity("OperationMaps.Domain.Entities.Catalog.FamilyParsingRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ComponentTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Example")
                        .HasColumnType("TEXT");

                    b.Property<string>("Pattern")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ComponentTypeId");

                    b.ToTable("FamilyParsingRules");
                });

            modelBuilder.Entity("OperationMaps.Domain.Entities.Catalog.Note", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("OperationMaps.Domain.Entities.Forms.Form", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ColumnGrouping")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DefaultLoadFactorParameterId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsUniversal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DefaultLoadFactorParameterId");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.ToTable("Froms");
                });

            modelBuilder.Entity("OperationMaps.Domain.Entities.Forms.FormParameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanBeLoadFactorBase")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FormId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RowNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SectionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SectionId");

                    b.HasIndex("FormId", "RowNumber")
                        .IsUnique();

                    b.ToTable("FormParameters");
                });

            modelBuilder.Entity("OperationMaps.Domain.Entities.Forms.FormSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FormId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FormId");

                    b.ToTable("FormSections");
                });

            modelBuilder.Entity("OperationMaps.Domain.Entities.Forms.FormValueColumn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FormId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FormId", "Key")
                        .IsUnique();

                    b.ToTable("FormValueColumns");
                });

            modelBuilder.Entity("OperationMaps.Domain.Entities.Projects.ParameterCellNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("NoteId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ParameterCellValueId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("NoteId");

                    b.HasIndex("ParameterCellValueId", "Order")
                        .IsUnique();

                    b.ToTable("ParameterCellNote");
                });

            modelBuilder.Entity("OperationMaps.Domain.Entities.Projects.ParameterCellValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FormParameterId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FormValueColumnId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RegimeGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FormParameterId");

                    b.HasIndex("FormValueColumnId");

                    b.HasIndex("RegimeGroupId", "FormParameterId", "FormValueColumnId")
                        .IsUnique();

                    b.ToTable("ParameterCellValue");
                });

            modelBuilder.Entity("OperationMaps.Domain.Entities.Projects.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreatedById")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceFileName")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.ToTable("Project");
                });

            modelBuilder.Entity("OperationMaps.Domain.Entities.Projects.ProjectComponent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ComponentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("DetectedCategory")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("MatchStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RawName")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ComponentId");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectComponent");
                });

            modelBuilder.Entity("OperationMaps.Domain.Entities.Projects.RegimeGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FormId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LoadFactorMin")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LoadFactorParameterId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FormId");

                    b.HasIndex("LoadFactorParameterId");

                    b.HasIndex("ProjectId");

                    b.ToTable("RegimeGroup");
                });

            modelBuilder.Entity("OperationMaps.Domain.Entities.Projects.RegimeGroupMember", b =>
                {
                    b.Property<int>("RegimeGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProjectComponentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("RegimeGroupId", "ProjectComponentId");

                    b.HasIndex("ProjectComponentId");

                    b.ToTable("RegimeGroupMember");
                });

            modelBuilder.Entity("OperationMaps.Domain.Entities.Users.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("OperationMaps.Domain.Entities.Catalog.Component", b =>
                {
                    b.HasOne("OperationMaps.Domain.Entities.Catalog.Family", "Family")
                        .WithMany("Components")
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Family");
                });

            modelBuilder.Entity("OperationMaps.Domain.Entities.Catalog.ComponentNote", b =>
                {
                    b.HasOne("OperationMaps.Domain.Entities.Catalog.Component", "Component")
                        .WithMany("ComponentNotes")
                        .HasForeignKey("ComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OperationMaps.Domain.Entities.Forms.FormParameter", "FormParameter")
                        .WithMany()
                        .HasForeignKey("FormParameterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OperationMaps.Domain.Entities.Catalog.Note", "Note")
                        .WithMany("ComponentNotes")
                        .HasForeignKey("NoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Component");

                    b.Navigation("FormParameter");

                    b.Navigation("Note");
                });

            modelBuilder.Entity("OperationMaps.Domain.Entities.Catalog.ComponentNtdValue", b =>
                {
                    b.HasOne("OperationMaps.Domain.Entities.Catalog.Component", "Component")
                        .WithMany("NtdValues")
                        .HasForeignKey("ComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OperationMaps.Domain.Entities.Forms.FormParameter", "FormParameter")
                        .WithMany()
                        .HasForeignKey("FormParameterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Component");

                    b.Navigation("FormParameter");
                });

            modelBuilder.Entity("OperationMaps.Domain.Entities.Catalog.ComponentPinValue", b =>
                {
                    b.HasOne("OperationMaps.Domain.Entities.Catalog.Component", "Component")
                        .WithMany("PinValues")
                        .HasForeignKey("ComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OperationMaps.Domain.Entities.Forms.FormParameter", "FormParameter")
                        .WithMany()
                        .HasForeignKey("FormParameterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Component");

                    b.Navigation("FormParameter");
                });

            modelBuilder.Entity("OperationMaps.Domain.Entities.Catalog.Family", b =>
                {
                    b.HasOne("OperationMaps.Domain.Entities.Catalog.ComponentType", "ComponentType")
                        .WithMany("Families")
                        .HasForeignKey("ComponentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ComponentType");
                });

            modelBuilder.Entity("OperationMaps.Domain.Entities.Catalog.FamilyForm", b =>
                {
                    b.HasOne("OperationMaps.Domain.Entities.Catalog.Family", "Family")
                        .WithMany("FamilyForms")
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OperationMaps.Domain.Entities.Forms.Form", "Form")
                        .WithMany()
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Family");

                    b.Navigation("Form");
                });

            modelBuilder.Entity("OperationMaps.Domain.Entities.Catalog.FamilyNote", b =>
                {
                    b.HasOne("OperationMaps.Domain.Entities.Catalog.Family", "Family")
                        .WithMany("FamilyNotes")
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OperationMaps.Domain.Entities.Forms.FormParameter", "FormParameter")
                        .WithMany()
                        .HasForeignKey("FormParameterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OperationMaps.Domain.Entities.Catalog.Note", "Note")
                        .WithMany("FamilyNotes")
                        .HasForeignKey("NoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Family");

                    b.Navigation("FormParameter");

                    b.Navigation("Note");
                });

            modelBuilder.Entity("OperationMaps.Domain.Entities.Catalog.FamilyNtdValue", b =>
                {
                    b.HasOne("OperationMaps.Domain.Entities.Catalog.Family", "Family")
                        .WithMany("NtdValues")
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OperationMaps.Domain.Entities.Forms.FormParameter", "FormParameter")
                        .WithMany()
                        .HasForeignKey("FormParameterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Family");

                    b.Navigation("FormParameter");
                });

            modelBuilder.Entity("OperationMaps.Domain.Entities.Catalog.FamilyParsingRule", b =>
                {
                    b.HasOne("OperationMaps.Domain.Entities.Catalog.ComponentType", "ComponentType")
                        .WithMany("ParsingRules")
                        .HasForeignKey("ComponentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ComponentType");
                });

            modelBuilder.Entity("OperationMaps.Domain.Entities.Forms.Form", b =>
                {
                    b.HasOne("OperationMaps.Domain.Entities.Forms.FormParameter", "DefaultLoadFactorParameter")
                        .WithMany()
                        .HasForeignKey("DefaultLoadFactorParameterId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("DefaultLoadFactorParameter");
                });

            modelBuilder.Entity("OperationMaps.Domain.Entities.Forms.FormParameter", b =>
                {
                    b.HasOne("OperationMaps.Domain.Entities.Forms.Form", "Form")
                        .WithMany("Parameters")
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OperationMaps.Domain.Entities.Forms.FormSection", "Section")
                        .WithMany("Parameters")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Form");

                    b.Navigation("Section");
                });

            modelBuilder.Entity("OperationMaps.Domain.Entities.Forms.FormSection", b =>
                {
                    b.HasOne("OperationMaps.Domain.Entities.Forms.Form", "Form")
                        .WithMany("Sections")
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Form");
                });

            modelBuilder.Entity("OperationMaps.Domain.Entities.Forms.FormValueColumn", b =>
                {
                    b.HasOne("OperationMaps.Domain.Entities.Forms.Form", "Form")
                        .WithMany("ValueColumns")
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Form");
                });

            modelBuilder.Entity("OperationMaps.Domain.Entities.Projects.ParameterCellNote", b =>
                {
                    b.HasOne("OperationMaps.Domain.Entities.Catalog.Note", "Note")
                        .WithMany()
                        .HasForeignKey("NoteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OperationMaps.Domain.Entities.Projects.ParameterCellValue", "ParameterCellValue")
                        .WithMany("Notes")
                        .HasForeignKey("ParameterCellValueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Note");

                    b.Navigation("ParameterCellValue");
                });

            modelBuilder.Entity("OperationMaps.Domain.Entities.Projects.ParameterCellValue", b =>
                {
                    b.HasOne("OperationMaps.Domain.Entities.Forms.FormParameter", "FormParameter")
                        .WithMany()
                        .HasForeignKey("FormParameterId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("OperationMaps.Domain.Entities.Forms.FormValueColumn", "FormValueColumn")
                        .WithMany()
                        .HasForeignKey("FormValueColumnId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("OperationMaps.Domain.Entities.Projects.RegimeGroup", "RegimeGroup")
                        .WithMany("CellValues")
                        .HasForeignKey("RegimeGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FormParameter");

                    b.Navigation("FormValueColumn");

                    b.Navigation("RegimeGroup");
                });

            modelBuilder.Entity("OperationMaps.Domain.Entities.Projects.Project", b =>
                {
                    b.HasOne("OperationMaps.Domain.Entities.Users.AppUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("OperationMaps.Domain.Entities.Projects.ProjectComponent", b =>
                {
                    b.HasOne("OperationMaps.Domain.Entities.Catalog.Component", "Component")
                        .WithMany()
                        .HasForeignKey("ComponentId");

                    b.HasOne("OperationMaps.Domain.Entities.Projects.Project", "Project")
                        .WithMany("Components")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Component");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("OperationMaps.Domain.Entities.Projects.RegimeGroup", b =>
                {
                    b.HasOne("OperationMaps.Domain.Entities.Forms.Form", "Form")
                        .WithMany()
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OperationMaps.Domain.Entities.Forms.FormParameter", "LoadFactorParameter")
                        .WithMany()
                        .HasForeignKey("LoadFactorParameterId");

                    b.HasOne("OperationMaps.Domain.Entities.Projects.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Form");

                    b.Navigation("LoadFactorParameter");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("OperationMaps.Domain.Entities.Projects.RegimeGroupMember", b =>
                {
                    b.HasOne("OperationMaps.Domain.Entities.Projects.ProjectComponent", "ProjectComponent")
                        .WithMany()
                        .HasForeignKey("ProjectComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OperationMaps.Domain.Entities.Projects.RegimeGroup", "RegimeGroup")
                        .WithMany("Members")
                        .HasForeignKey("RegimeGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProjectComponent");

                    b.Navigation("RegimeGroup");
                });

            modelBuilder.Entity("OperationMaps.Domain.Entities.Catalog.Component", b =>
                {
                    b.Navigation("ComponentNotes");

                    b.Navigation("NtdValues");

                    b.Navigation("PinValues");
                });

            modelBuilder.Entity("OperationMaps.Domain.Entities.Catalog.ComponentType", b =>
                {
                    b.Navigation("Families");

                    b.Navigation("ParsingRules");
                });

            modelBuilder.Entity("OperationMaps.Domain.Entities.Catalog.Family", b =>
                {
                    b.Navigation("Components");

                    b.Navigation("FamilyForms");

                    b.Navigation("FamilyNotes");

                    b.Navigation("NtdValues");
                });

            modelBuilder.Entity("OperationMaps.Domain.Entities.Catalog.Note", b =>
                {
                    b.Navigation("ComponentNotes");

                    b.Navigation("FamilyNotes");
                });

            modelBuilder.Entity("OperationMaps.Domain.Entities.Forms.Form", b =>
                {
                    b.Navigation("Parameters");

                    b.Navigation("Sections");

                    b.Navigation("ValueColumns");
                });

            modelBuilder.Entity("OperationMaps.Domain.Entities.Forms.FormSection", b =>
                {
                    b.Navigation("Parameters");
                });

            modelBuilder.Entity("OperationMaps.Domain.Entities.Projects.ParameterCellValue", b =>
                {
                    b.Navigation("Notes");
                });

            modelBuilder.Entity("OperationMaps.Domain.Entities.Projects.Project", b =>
                {
                    b.Navigation("Components");
                });

            modelBuilder.Entity("OperationMaps.Domain.Entities.Projects.RegimeGroup", b =>
                {
                    b.Navigation("CellValues");

                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
